const BASE_URL = 'http://localhost:3000';
// const BASE_URL = 'https://api.movie.nomorepartiesxyz.ru';

const BREAKPOINT_1280 = 1280;
const BREAKPOINT_768 = 768;
const BREAKPOINT_480 = 480;

const VISIBLE_MOVIES_12 = 12;
const VISIBLE_MOVIES_8 = 8;
const VISIBLE_MOVIES_5 = 5;

const ADD_VISIBLE_MOVIES_4 = 4;
const ADD_VISIBLE_MOVIES_2 = 2;
const ADD_VISIBLE_MOVIES_5 = 5;

const SHORT_MOVIE_TIME = 40;

export {
    BASE_URL,
    BREAKPOINT_1280,
    BREAKPOINT_768,
    BREAKPOINT_480,
    VISIBLE_MOVIES_12,
    VISIBLE_MOVIES_8,
    VISIBLE_MOVIES_5,
    ADD_VISIBLE_MOVIES_4,
    ADD_VISIBLE_MOVIES_2,
    ADD_VISIBLE_MOVIES_5,
    SHORT_MOVIE_TIME,
};